title: BoringPass
description: Privacy-first password management. No cloud, no compromise.
url: "https://gg-241.github.io"
baseurl: "/boringpass-site"

# GitHub Pages settings
theme: null
plugins: []

# Exclude files that should not be published
exclude:
  - .gitignore
  - README.md
